### PR TITLE
feat: compile to esm and cjs

### PR DESCRIPTION
**Pull request by janek26**
This PR aims to support commonjs and esm targets from one npm package, so this package can be used in more environments

### CODE REVIEW

**Comment by janek26** [comment]
okay will do asap

**Comment by janek26** [comment]
please have another look @paulmillr

**Comment by dhruvkelawala** [comment]
Yes please!

**Comment by paulmillr** [comment]
@janek26 @dhruvkelawala do you actually need common.js? It's getting painful to maintain common.js with the recent changes

**Pull request merged**
